aws_region = "us-west-2"
#aws_access_key	= ""
#aws_secret_key	= ""
mode = "prometheus"
#node1_mode		= "node_exporter-1"
#node2_mode		= "node_exporter-2"
environment = "test"
keypair     = "west2"
